# Generated by Django 5.2.15 on 2026-07-07 04:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailJob',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('job_type', models.CharField(blank=True, default='', max_length=120)),
                ('to_email', models.CharField(blank=True, default='', max_length=320)),
                ('status', models.CharField(blank=True, default='pending', max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('price_from', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(max_length=320)),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('industry', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(blank=True, default='new', max_length=60)),
                ('stage', models.CharField(blank=True, default='lead', max_length=60)),
                ('engagement_level', models.IntegerField(default=0)),
                ('recommended_product', models.CharField(blank=True, default='', max_length=255)),
                ('data_quality', models.JSONField(default=dict)),
                ('validation', models.JSONField(default=dict)),
                ('score', models.IntegerField(default=30)),
                ('tier', models.CharField(blank=True, default='Cold', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=120)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailjob')),
            ],
        ),
    ]
