# Generated by Django 5.2.15 on 2026-07-07 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campaign_suppressionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='email_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_prospects', to='core.campaign'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='follow_up_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('outreach_sent', 'Outreach sent'), ('follow_up_scheduled', 'Follow-up scheduled'), ('in_conversation', 'In conversation'), ('won', 'Won'), ('lost', 'Lost')], default='not_started', max_length=40),
        ),
        migrations.AddField(
            model_name='prospect',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='prospect',
            name='matched_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_prospects', to='core.product'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='verified_email',
            field=models.EmailField(blank=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='prospect',
            name='why_fit',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CampaignTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('industry', models.CharField(blank=True, default='', max_length=120)),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('fit_notes', models.TextField(blank=True, default='')),
                ('matched_products', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='core.campaign')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'company'), name='uniq_campaign_target_company')],
            },
        ),
        migrations.CreateModel(
            name='ProspectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cto', 'CTO'), ('ceo', 'CEO'), ('head_of_engineering', 'Head of Engineering'), ('product_director', 'Product Director'), ('partnership_manager', 'Partnership Manager'), ('business_development_director', 'Business Development Director')], max_length=60)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=320)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.prospect')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prospect', 'role'), name='uniq_prospect_contact_role')],
            },
        ),
    ]
