# Generated by Django 5.2.15 on 2026-07-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_strategic_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntarget',
            name='public_contact_email',
            field=models.EmailField(blank=True, default='', max_length=320),
        ),
    ]
