# Generated by Django 5.2.15 on 2026-07-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_top10_real_outreach_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='compliance_basis',
            field=models.CharField(blank=True, choices=[('consent', 'Consent'), ('legitimate_interest', 'Legitimate interest'), ('contractual_necessity', 'Contractual necessity')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='prospect',
            name='compliance_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='source_provider',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='prospect',
            name='source_record_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
