# Generated by Django 5.2.15 on 2026-07-07 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prospect_compliance_basis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('outreach', 'Outreach'), ('read_only', 'Read only')], default='read_only', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=120)),
                ('actor', models.CharField(blank=True, default='system', max_length=255)),
                ('resource_type', models.CharField(blank=True, default='', max_length=120)),
                ('resource_id', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('endpoint', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_code', models.IntegerField(default=200)),
                ('response_body', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='emailjob',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emailjob',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailjob',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailjob',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='emailjob',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='emailjob',
            index=models.Index(fields=['status', 'available_at'], name='emailjob_status_available_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['country', 'industry'], name='prospect_country_industry_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['follow_up_status', 'tier'], name='prospect_followup_tier_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['email_campaign', 'score'], name='prospect_campaign_score_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_emailjob_idempotency'),
        ),
    ]
